### ISSUE TITLE
Pusta linia wywala konwerter

### ISSUE THREAD

**Issue by michzimny** [emkael/deal-convert#4]
Jeśli po wierszu `% PBN 1.0` wstawi się pustą linię, to konwersja wywala się. Do tego wyjątek wylatuje w dziwnym miejscu, na oko sporo za późno. Pewnie wcześniej powinna być gdzieś chociaż asercja sprawdzająca, czy board_no nie jest None-em.

Przykładowy PBN:
```
% PBN 1.0

[Generator "Big Deal version 1.1.JFR"]
[Event "Event"]
[Board "1"]
[Dealer "N"]
[Vulnerable "None"]
[Deal "N:JT872.JT3.J72.J7 K965.Q75.Q8643.4 AQ4.K964..KQ6532 3.A82.AKT95.AT98"]
[Ability "N:57628 E:856B5 S:57628 W:756A4"]
[Minimax "5DE-400"]
```

Wyjątek:
```
Traceback (most recent call last):
  File "/opt/emkael-deal-convert/deal-converter.py", line 25, in <module>
    converter.output(arguments.output)
  File "/opt/emkael-deal-convert/dealconvert/__init__.py", line 11, in output
    deal_set = sorted(self.parser.parse(self.input), key=lambda d:d.number)
  File "/opt/emkael-deal-convert/dealconvert/formats/__init__.py", line 8, in parse
    return self.parse_content(content)
  File "/opt/emkael-deal-convert/dealconvert/formats/pbn.py", line 74, in parse_content
    deal_dto.dealer = deal_dto.get_dealer(deal_dto.number)
  File "/opt/emkael-deal-convert/dealconvert/dto.py", line 25, in get_dealer
    return (board_no - 1) % 4
TypeError: unsupported operand type(s) for -: 'NoneType' and 'int'
```

**Comment by emkael** [comment]
Wygląda na dwa niezależne problemy.

Pierwszy: nie uzupełniać założeń/rozdającego, jeśli rozdanie nie ma numeru. I to powinno rozwiązać rzeczony problem.
Drugi: nie importować z PBN rozdań, które nie zawierają żadnego nazwanego pola.

**Comment by emkael** [comment]
Przy czym ten drugi problem na oko chyba jednak nie jest problemem.
